apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/REPLACE_WITH_YOUR_USERNAME/k8s-mario.git
    targetRevision: develop
    path: gitops/overlays/dev
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
